name = "FiniteDiffWENO5"
uuid = "4b1b4241-afed-47c3-a843-c6e03821b375"
version = "0.0.3"
authors = ["Hugo Dominguez  <hdomingu@uni-mainz.de>"]

[deps]
MuladdMacro = "46d2c3a1-f734-5fdb-9937-b9b9aeba4221"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[weakdeps]
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
Chmy = "33a72cf0-4690-46d7-b987-06506c2248b9"

[extensions]
KAExt = ["KernelAbstractions"]
ChmyExt = ["KernelAbstractions", "Chmy"]

[compat]
Chmy = "0.1"
KernelAbstractions = "0.9"
MuladdMacro = "0.2"
UnPack = "1.0"
julia = "1.10"
